### ISSUE TITLE
webpack warning in a nodejs environment 

### ISSUE THREAD

**Issue by Wyzix33** [devrafalko/exact-math#10]
Hi,
I'm using exact-math in a nodejs environment, it's a very small project, without webpack, and i'm getting this warning when i run``` npm install ```after adding exact-math lib:
```
npm WARN terser-webpack-plugin@1.4.1 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
```
Can you please move terser-webpack-plugin to devDependencies?

Thanks

**Comment by devrafalko** [comment]
Actually, I should have removed `terser-webpack-plugin` with the last update as it was useless, but forgot 🤦. I got rid of that plugin in the new `2.1.2` version.

**Comment by Wyzix33** [comment]
Thanks
