### ISSUE TITLE
Superfluous files in the NPM package

### ISSUE THREAD

**Issue by chocolateboy** [devrafalko/exact-math#18]
There are lots of [extraneous files](https://unpkg.com/browse/exact-math@2.2.0/) in the exact-math [tarball](https://registry.npmjs.org/exact-math/-/exact-math-2.2.0.tgz), including the [`simulator`](https://github.com/devrafalko/exact-math/tree/v2.0.0/simulator) directory, tests, source code, and config files — none of which are needed by consumers of the package.

The code itself is ~ 100 KB, but the package size is 1.2 MB. I suggest using the [`files` array](https://docs.npmjs.com/files/package.json#files) in your `package.json` to only include the files you intend to publish.

**Comment by devrafalko** [comment]
9e61f18 
OK. I've added `.npmignore` file that excludes unnecessary files.
