### ISSUE TITLE
Hello 👋 Can I...

### ISSUE THREAD

**Issue by arguiot** [devrafalko/exact-math#2]
Hello 👋, I really like ❤️ this project. I don’t know on what you’re working on right now, but if you have time to read this, this my question:

I’m currently working on a framework called DisplayJS, and I wanted to implement some “exact-math” functions. I looked 👀 on the internet to see if someone has already worked on something similar. And I found your project 😜. Is it possible to add a version of “exact-math” in DisplayJS?
> Of course, your name will be added in the contributors list 😊

Do you accept?

**Comment by devrafalko** [comment]
sure ;)

**Comment by arguiot** [comment]
Thank you 😊

**Comment by arguiot** [comment]
By the way, you can check the project and leave a star ⭐️ 😉

**Comment by arguiot** [comment]
https://display.js.org
