### ISSUE TITLE
Incorrect result from exponential notation division.

### ISSUE THREAD

**Issue by joofjang** [devrafalko/exact-math#6]
I've found incorrect results from exponential notation division when using the formula method.

Here is how to reproduce.
```
const exactMath = require('exact-math');
exactMath.formula('1e+42 / 10'); // The result is 1e+83.
```

I've tested with string-math and it works correctly.

This library is great. Thanks for your effort.

**Comment by devrafalko** [comment]
I've just published the `2.0.1` version that fixes this issue. Thank you for your report.
