### ISSUE TITLE
exactMath.round with specific number of decimals?

### ISSUE THREAD

**Issue by Wyzix33** [devrafalko/exact-math#8]
Hi, 
exactMath.round works great, but i want to be able to keep the decimals even if they are 0, 
```
let test = exactMath.round("10", -2, { returnString: true }); // returns 10, and i need 10.00
```
any way to do that?

I tried ```exactMath.round("10", -2).toFixed(2)```
without ``` { returnString: true }``` but got some unwanted rounds from toFixed...

For now i use ```parseFloat(test).toFixed(2)``` or ```(test*1).toFixed(2)``` but it would be great to get this from the round function.

Also a check to see if a string is a valid number or not might be good :) .
```
isNumeric(n) {
   return !isNaN(parseFloat(n)) && isFinite(n);
}
```
seems to work for my test cases.
Thanks

**Comment by devrafalko** [comment]
Reinstall `exact-math` with the new `@2.1.0` version. It has the new `trim` config property.

    let test = exactMath.round("10", -2, { returnString: true, trim: false }); //10.00

**Comment by Wyzix33** [comment]
It works!
Thanks
